app = "app-delicate-bush-2268"
primary_region = "ewr"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1